AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Counter application using DynamoDB, Lambda, and API Gateway

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    Environment:
      Variables:
        TABLE_NAME: !Ref CounterTable

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - https://www.mabrouk-engineering.com
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
      DisableExecuteApiEndpoint: true
      DefaultRouteSettings:
        ThrottlingBurstLimit: 5
        ThrottlingRateLimit: 10
      Domain:
        DomainName: api-counter.mabrouk-engineering.com
        CertificateArn: arn:aws:acm:us-east-1:806321741962:certificate/6c3675c7-da75-4533-8130-41860bcddceb
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: Z0173812Y53L6HX55BC

  # DynamoDB Table
  CounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: counter-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Function for Counter Operations
  CounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./function
      Handler: counter.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CounterTable
      Events:
        GetCounter:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /counter
            Method: GET
        IncrementCounter:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /counter/increment
            Method: POST
        DecrementCounter:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /counter/decrement
            Method: POST
        ResetCounter:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /counter/reset
            Method: POST

Outputs:
  ApiEndpoint:
    Description: HTTP API endpoint URL
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com"
  
  CustomDomainEndpoint:
    Description: Custom domain endpoint URL
    Value: "https://api-counter.mabrouk-engineering.com"
  
  CounterTableName:
    Description: DynamoDB table name
    Value: !Ref CounterTable
